CREATE TABLE VIDEOS(
  ID          INTEGER         NOT NULL,
  NAME        VARCHAR(60)     NOT NULL,
  DATA        bytea           NOT NULL
);

ALTER TABLE VIDEOS ADD CONSTRAINT PK_VIDEO PRIMARY KEY(ID);


CREATE SEQUENCE SQ_VIDEO;